### PR TITLE
Create SECURITY.mdluku

### PR DESCRIPTION
**Pull request by Lukaszreszka130**

### CODE REVIEW

**Comment by Lukaszreszka130** [comment]
:)

**Comment by GWLTd** [comment]
> :)

Be

**Comment by hanhungsoo** [comment]
0xD169791fB67C3D0Dcfec5aCe0f4b266a8b19dEdf

**Comment by hanhungsoo** [comment]
0xD169791fB67C3D0Dcfec5aCe0f4b266a8b19dEdf

**Review by Mulligani777 — APPROVED** [review]

**Comment by just-toby** [comment]
this doesn't seem relevant

**Pull request closed without merging**
